### ISSUE TITLE
[Feature Request] Implement Bypasser in popular wrappers such as Tinfoil for Facebook

### ISSUE THREAD

**Issue by rodneyrod** [gsurrel/MessengerBypasser#1]

**Comment by gsurrel** [comment]
I guess that's more the job of the third-parties to do that :)
If not, what are you expecting exactly from this app?

There is already such a bug opened for that for Tinfoil: https://github.com/velazcod/Tinfoil-Facebook/issues/84

**Comment by rodneyrod** [comment]
Sorry about that, posted in the wrong project
