### ISSUE TITLE
Also catch "open Google Play" intent

### ISSUE THREAD

**Issue by crxed9** [gsurrel/MessengerBypasser#3]
When using Chrome browser and mobile Facebook site, tapping the messages icon will open the Google Play Store to the Messenger app. Can you also bypass this?

**Comment by gsurrel** [comment]
I tried to get that working but I couldn't, I'll try to get it done. It's quite surprisingly harder than expected.

**Comment by singpolyma** [comment]
I currently set User Agent to FirefoxOS to bypass this, but would be nice to have another way

**Comment by gsurrel** [comment]
As [SlimSocial for Facebook](https://f-droid.org/repository/browse/?fdfilter=SlimSOcial&fdid=it.rignanese.leo.slimfacebook) is a wrapper which avoid all the problems encountered by Tinfoil, I'm no longer supporting my app.
