### ISSUE TITLE
Is this meant to allow messages to be viewed or only prevent the crash?

### ISSUE THREAD

**Issue by caviidae** [gsurrel/MessengerBypasser#4]
It prevents the crash for me, which is great, but still no way to read the messages. Is that the intention or am I missing something?

**Comment by gsurrel** [comment]
Could you explain why you can't read the messages?

If it's because you have the big "Your conversations are moving to Messenger", you can close the dialog with the cross in the top-right corner of the webpage. If it's because of something else, maybe a screenshot can help :)

**Comment by its-schmii** [comment]
@gsurrel That cross in the top right corner was removed. At least a portion of users is already affected, global rollout of "force messenger" has already been announced by FB.

**Comment by gsurrel** [comment]
Indeed, I've been victim of that just yesterday. The only workaround I've found for be now is to install the [Lightning browser](https://f-droid.org/repository/browse/?fdfilter=lightning&fdid=acr.browser.lightning) using a custom user agent pretending to run Android 2.3. When doing that, everything seems to work well.

```
Mozilla/5.0 (Linux; U; Android 2.3; en-us; Nexus 4 Build/JOP24G) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

It doesn't with Firefox Mobile with the tweaker UA, there are heavy display issues. Therefore, it seems that my MessengerBypasser is useful only for a few days before forcing the migration to Messenger, unless when tweaking the UA for the browser used to pretend to have an Android version unsupported by Messenger. 

I could also build some Messages specific wrapper but it's not really interesting when it can fixed upstream bu spoofing the UA.
